version: '2'
volumes: 
    resin-data:
services:
  # Connectivy looks after GSM modems and overall connection management
  connectivity:
    build: ./connectivity
    privileged: true
    restart: always
    volumes: 
      - 'resin-data:/data'
  # Ubuntu is a basic container without drivers, mainly used for development
  ubuntu:
    build: ./ubuntu
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base is a basic container with CUDA drivers
  cudabase:
    build: ./cudabase
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base + TensorRT + OpenCV4Tegra container
  opencv4tegra:
    build: ./opencv4tegra
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base + OpenCV4Tegra + TensorRT (same as opencv4tegra container)
  tensorrt:
    build: ./tensorrt
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base + OpenCV4Tegra + TensorRT + Chainer container
  chainer:
    build: ./chainer
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base + OpenCV4Tegra + TensorRT + NVIDIA caffee container
  caffee:
    build: ./caffee
    privileged: true
    restart: always
    depends_on:
      - connectivity
  # Cuda Base + OpenCV4Tegra + TensorRT + TensorFlow container
  tensorflow:
    build: ./tensorflow
    privileged: true
    restart: always
    depends_on:
      - connectivity
  inference:
    build: ./inference
    privileged: true
    restart: always
    depends_on:
      - connectivity
  digits:
    build: ./digits
    privileged: true
    restart: always
    depends_on:
      - connectivity
    expose:
      - "5001"